package convert

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParsePkgInfo(t *testing.T) {
	content := `# Generated by makepkg
pkgname = neovim
pkgver = 0.10.0-1
pkgdesc = Fork of Vim aiming to improve user experience
url = https://neovim.io
builddate = 1704067200
packager = Arch Linux Packager <packager@archlinux.org>
size = 5242880
arch = x86_64
depend = libluv
depend = libuv
depend = msgpack-c
optdepend = python-pynvim: for plugins
provides = vim
conflict = vim
`

	info := ParsePkgInfo(content)

	if info.PkgName != "neovim" {
		t.Errorf("Expected pkgname 'neovim', got '%s'", info.PkgName)
	}
	if info.PkgVer != "0.10.0-1" {
		t.Errorf("Expected pkgver '0.10.0-1', got '%s'", info.PkgVer)
	}
	if info.PkgDesc != "Fork of Vim aiming to improve user experience" {
		t.Errorf("Expected pkgdesc mismatch, got '%s'", info.PkgDesc)
	}
	if len(info.Depends) != 3 {
		t.Errorf("Expected 3 depends, got %d", len(info.Depends))
	}
	if len(info.OptDepends) != 1 {
		t.Errorf("Expected 1 optdepend, got %d", len(info.OptDepends))
	}
	if len(info.Provides) != 1 {
		t.Errorf("Expected 1 provides, got %d", len(info.Provides))
	}
	if len(info.Conflicts) != 1 {
		t.Errorf("Expected 1 conflict, got %d", len(info.Conflicts))
	}
	if info.Size != 5242880 {
		t.Errorf("Expected size 5242880, got %d", info.Size)
	}
}

func TestParsePkgInfo_EmptyContent(t *testing.T) {
	info := ParsePkgInfo("")
	if info.PkgName != "" {
		t.Error("Expected empty pkgname")
	}
}

func TestExtractFunction(t *testing.T) {
	script := `
post_install() {
	echo "Installing..."
	systemctl daemon-reload
}

pre_remove() {
	systemctl stop myservice
}
`

	postInstall := extractFunction(script, "post_install")
	if !strings.Contains(postInstall, "echo") {
		t.Errorf("Expected post_install to contain echo, got '%s'", postInstall)
	}
	if !strings.Contains(postInstall, "systemctl daemon-reload") {
		t.Errorf("Expected post_install to contain systemctl, got '%s'", postInstall)
	}

	preRemove := extractFunction(script, "pre_remove")
	if !strings.Contains(preRemove, "systemctl stop") {
		t.Errorf("Expected pre_remove to contain systemctl stop, got '%s'", preRemove)
	}

	nonExistent := extractFunction(script, "nonexistent")
	if nonExistent != "" {
		t.Errorf("Expected empty string for nonexistent function, got '%s'", nonExistent)
	}
}

func TestDetectPackageFormat(t *testing.T) {
	tests := []struct {
		path     string
		expected string
	}{
		{"package.shed", "shed"},
		{"neovim-0.10.0-1-x86_64.pkg.tar.zst", "pacman-zst"},
		{"vim-9.0.0-1-x86_64.pkg.tar.xz", "pacman-xz"},
		{"vim-9.0.0-1-x86_64.pkg.tar.gz", "pacman-gz"},
		{"package.deb", "deb"},
		{"package.rpm", "rpm"},
		{"unknown.file", "unknown"},
	}

	for _, tc := range tests {
		result := DetectPackageFormat(tc.path)
		if result != tc.expected {
			t.Errorf("DetectPackageFormat(%s) = %s, want %s", tc.path, result, tc.expected)
		}
	}
}

func TestPackageConverter_NewPackageConverter(t *testing.T) {
	converter := NewPackageConverter()
	if converter.cacheDir == "" {
		t.Error("Expected non-empty cacheDir")
	}
	if !strings.Contains(converter.cacheDir, "shedman") {
		t.Errorf("Expected cacheDir to contain 'shedman', got '%s'", converter.cacheDir)
	}
}

func TestPackageConverter_SetCacheDir(t *testing.T) {
	converter := NewPackageConverter()
	customDir := "/tmp/test-cache"
	converter.SetCacheDir(customDir)
	if converter.cacheDir != customDir {
		t.Errorf("Expected cacheDir '%s', got '%s'", customDir, converter.cacheDir)
	}
}

func TestPackageConverter_ConvertPacmanToShed_Integration(t *testing.T) {
	// Skip if tar is not available
	if !CommandExists("tar") {
		t.Skip("tar not available, skipping integration test")
	}

	// Create a temporary directory for testing
	tempDir, err := os.MkdirTemp("", "converter-test")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tempDir)

	// Create a mock pacman package structure
	mockPkgDir := filepath.Join(tempDir, "mock-pkg")
	os.MkdirAll(filepath.Join(mockPkgDir, "usr", "bin"), DirPermissions)
	os.WriteFile(filepath.Join(mockPkgDir, "usr", "bin", "testbin"), []byte("#!/bin/sh\necho test"), ExecPermissions)

	// Create .PKGINFO
	pkgInfo := `pkgname = testpkg
pkgver = 1.0.0-1
pkgdesc = Test package
arch = x86_64
depend = glibc
`
	os.WriteFile(filepath.Join(mockPkgDir, ".PKGINFO"), []byte(pkgInfo), FilePermissions)

	// Create .INSTALL
	install := `post_install() {
	echo "Installed!"
}
`
	os.WriteFile(filepath.Join(mockPkgDir, ".INSTALL"), []byte(install), FilePermissions)

	// Create the pacman package
	pacmanPkg := filepath.Join(tempDir, "testpkg-1.0.0-1-x86_64.pkg.tar.gz")

	// Use tar to create the package
	converter := NewPackageConverterWithCacheDir(tempDir)
	err = converter.executor([]string{"tar", "-czf", pacmanPkg, "-C", mockPkgDir, "."})
	if err != nil {
		t.Fatalf("Failed to create mock package: %v", err)
	}

	// Test conversion
	shedPath, err := converter.ConvertPacmanToShed(pacmanPkg)
	if err != nil {
		t.Fatalf("ConvertPacmanToShed failed: %v", err)
	}

	if shedPath == "" {
		t.Error("Expected non-empty shed path")
	}

	// Verify .shed file exists
	if _, err := os.Stat(shedPath); os.IsNotExist(err) {
		t.Errorf("Shed file does not exist: %s", shedPath)
	}

	// Extract and verify manifest
	shedExtract := filepath.Join(tempDir, "shed-extract")
	os.MkdirAll(shedExtract, DirPermissions)
	err = converter.executor([]string{"tar", "-xf", shedPath, "-C", shedExtract})
	if err != nil {
		t.Fatalf("Failed to extract shed package: %v", err)
	}

	// Check manifest exists
	manifestPath := filepath.Join(shedExtract, "manifest.toml")
	if _, err := os.Stat(manifestPath); os.IsNotExist(err) {
		t.Error("manifest.toml not found in shed package")
	}

	// Check files directory exists
	filesDir := filepath.Join(shedExtract, "files")
	if _, err := os.Stat(filesDir); os.IsNotExist(err) {
		t.Error("files directory not found in shed package")
	}

	// Check hooks directory exists
	hooksDir := filepath.Join(shedExtract, "hooks")
	if _, err := os.Stat(hooksDir); os.IsNotExist(err) {
		t.Error("hooks directory not found in shed package")
	}

	// Check post-install hook exists
	postInstallHook := filepath.Join(hooksDir, "post-install.sh")
	if _, err := os.Stat(postInstallHook); os.IsNotExist(err) {
		t.Error("post-install.sh not found in hooks")
	}
}
