name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: System Update & Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git go golangci-lint bubblewrap restic

      - uses: actions/checkout@v4

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory '*'

      - name: Lint
        env:
          GOFLAGS: "-buildvcs=false"
        run: golangci-lint run

      - name: Test
        run: go test -v -race ./...

      - name: Build
        run: make build
